### ISSUE TITLE
Fail gracefully on rsync step failure

### ISSUE THREAD

**Issue by icarito** [SolydXK/live-installer-3#1]
Was bitten by a corrupted USB, but without a useful error.

**Comment by ArjenBalfoort** [comment]
I'll copy what I've posted on the forum to your post if anyone comes here:

> rsync errors are catched for the target partition but it is oblivious of I/O errors on the source partition. It'll simply hang on a damaged block.
> 
> Best way to prevent this is to check the integrity after the ISO has been written to the USB.
> If you've used dd like this:
> `sudo dd if=solydk_9_64_201801.iso of=/dev/sdc bs=4M && sync`
> then check the USB:
> `sudo head -c $(stat -c '%s' solydk_9_64_201801.iso) /dev/sdc | sha256sum`
> and compare that with the solydk_9_64_201801.iso.sha256 file.

Closing this issue: cannot fix.
